<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{ $engagement->title }} - Engagement Details</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Tailwind CSS -->
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">

  <style>
    @media print {
      .no-print {
        display: none !important;
      }
    }
  </style>
</head>
<body class="bg-gray-50 text-gray-900 font-sans antialiased min-h-screen p-6">

  <div class="max-w-4xl mx-auto bg-white rounded-lg shadow-md border border-gray-300 p-8 print:border-none print:shadow-none">

    <!-- Header Section -->
    <div class="flex justify-between items-center mb-6 border-b pb-4 border-gray-200">
      <div class="flex items-center gap-4">
        <img src="{{ asset('images/citizen.png') }}" alt="Organization Logo" class="h-14 w-14 object-contain">
        <div>
          <h1 class="text-2xl font-bold">Citizen Engagement Office</h1>
          <p class="text-sm text-gray-500">Empowering Communities through Active Engagement</p>
        </div>
      </div>
      <button onclick="window.print()" class="no-print bg-gray-800 hover:bg-black text-white px-4 py-2 rounded text-sm">
        🖨️ Print
      </button>
    </div>

    <!-- Engagement Detail Section -->
    <div>
      <h2 class="text-xl font-semibold text-gray-800 mb-4">Engagement Information</h2>
      <dl class="divide-y divide-gray-200 text-sm">
        <div class="py-3 grid grid-cols-1 sm:grid-cols-3 gap-4">
          <dt class="font-medium text-gray-600">Title</dt>
          <dd class="sm:col-span-2">{{ $engagement->title }}</dd>
        </div>
        <div class="py-3 grid grid-cols-1 sm:grid-cols-3 gap-4">
          <dt class="font-medium text-gray-600">Host</dt>
          <dd class="sm:col-span-2">{{ $engagement->host }}</dd>
        </div>
        <div class="py-3 grid grid-cols-1 sm:grid-cols-3 gap-4">
          <dt class="font-medium text-gray-600">Start Date</dt>
          <dd class="sm:col-span-2">{{ \Carbon\Carbon::parse($engagement->start_date)->format('F d, Y') }}</dd>
        </div>
        <div class="py-3 grid grid-cols-1 sm:grid-cols-3 gap-4">
          <dt class="font-medium text-gray-600">End Date</dt>
          <dd class="sm:col-span-2">{{ \Carbon\Carbon::parse($engagement->end_date)->format('F d, Y') }}</dd>
        </div>
        <div class="py-3 grid grid-cols-1 sm:grid-cols-3 gap-4">
          <dt class="font-medium text-gray-600">Description</dt>
          <dd class="sm:col-span-2 whitespace-pre-wrap">{{ $engagement->description }}</dd>
        </div>
      </dl>
    </div>

    

    <!-- Footer Section -->
    <div class="mt-10 pt-4 border-t border-gray-200 text-xs text-gray-500 flex justify-between">
      <span>Generated by Citizen Engagement Platform</span>
      <span>Date Printed: {{ \Carbon\Carbon::now()->format('F d, Y h:i A') }}</span>
    </div>
  </div>

</body>
</html>
